name: whisper-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - cffi=1.15.1
  - gettext=0.19.8.1
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libflac=1.3.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libogg=1.3.4
  - libopenblas=0.3.20
  - libopus=1.3.1
  - libsndfile=1.0.31
  - libstdcxx-ng=11.2.0
  - libvorbis=1.3.7
  - ncurses=6.3
  - numpy=1.22.3
  - openssl=1.1.1q
  - pip=22.1.2
  - pycparser=2.21
  - pysoundfile=0.10.3.post1
  - python=3.8.13
  - python_abi=3.8
  - readline=8.1.2
  - sqlite=3.39.2
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - absl-py==1.3.0
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - appdirs==1.4.4
    - async-timeout==4.0.2
    - attrs==22.1.0
    - audioread==3.0.0
    - black==19.10b0
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - click==8.0.4
    - contourpy==1.0.5
    - cycler==0.11.0
    - datasets==2.5.1
    - decorator==5.1.1
    - dill==0.3.5.1
    - entrypoints==0.3
    - evaluate==0.3.0
    - ffmpeg-python==0.2.0
    - filelock==3.8.0
    - fire==0.4.0
    - flake8==3.7.9
    - fonttools==4.37.4
    - frozenlist==1.3.1
    - fsspec==2022.8.2
    - future==0.18.2
    - google-auth==2.14.1
    - google-auth-oauthlib==0.4.6
    - grpcio==1.50.0
    - huggingface-hub==0.10.1
    - hyperpyyaml==1.0.1
    - idna==3.4
    - importlib-metadata==4.12.0
    - jiwer==2.5.1
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - levenshtein==0.20.2
    - librosa==0.9.2
    - lightning-utilities==0.3.0
    - llvmlite==0.39.1
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.1
    - mccabe==0.6.1
    - more-itertools==8.14.0
    - multidict==6.0.2
    - multiprocess==0.70.13
    - numba==0.56.2
    - oauthlib==3.2.2
    - packaging==21.3
    - pandas==1.5.0
    - pathspec==0.10.1
    - pillow==9.2.0
    - pluggy==0.13.1
    - pooch==1.6.0
    - protobuf==3.20.1
    - py==1.11.0
    - pyarrow==9.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.5.0
    - pyflakes==2.1.1
    - pyparsing==3.0.9
    - pytest==5.4.1
    - python-dateutil==2.8.2
    - pytorch-lightning==1.8.1
    - pytz==2022.2.1
    - pyyaml==6.0
    - rapidfuzz==2.13.2
    - regex==2022.9.13
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - resampy==0.4.2
    - responses==0.18.0
    - rsa==4.9
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.6
    - scikit-learn==1.1.3
    - scipy==1.9.1
    - sentencepiece==0.1.97
    - setuptools==59.8.0
    - six==1.16.0
    - speechbrain==0.5.13
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - termcolor==2.1.1
    - threadpoolctl==3.1.0
    - tokenizers==0.12.1
    - toml==0.10.2
    - torch==1.11.0
    - torchaudio==0.11.0
    - torchmetrics==0.10.3
    - torchvision==0.12.0
    - transformers
    - tqdm==4.64.1
    - typed-ast==1.5.4
    - typing-extensions==4.3.0
    - urllib3==1.26.12
    - wcwidth==0.2.5
    - werkzeug==2.2.2
    - xxhash==3.0.0
    - yamllint==1.23.0
    - yarl==1.8.1
    - zipp==3.8.1
    # Local speechbrain package
    - -e ../../../